### ISSUE TITLE
Does not work with laravel 5.1

### ISSUE THREAD

**Issue by pepijnolivier** [unikent/taggedFileCache#2]
Hi, I was hoping I could use this package as a temporary solution for an environment where memcached is yet to be set up.

Issues with laravel 5.1:
- trait `RetrievesMultipleKeys` is missing in Laravel 5.1
- Error: `Class 'Unikent\Jobs\FlushTagFromFileCacheJobHandler not found`

Seems like the package is currently unusable for Laravel 5.1.

**Comment by gjmh-unikent** [comment]
thanks for the feedback, we have only been using this with lumen recently and it looks like some of the dependencies differ, have fixed these issues and tested with a fresh copy of laravel 5.1.33.

https://github.com/unikent/taggedFileCache/releases/tag/1.0.7

Please let me know if you have any further problems.

**Comment by pepijnolivier** [comment]
@gjmh-unikent Yep, solved! Thanks a lot!
