### ISSUE TITLE
Cache not being cleared by console command

### ISSUE THREAD

**Issue by boydcl** [unikent/taggedFileCache#3]
The cache for the tfile store is not being cleared when running `php artisan cache:clear`. Only when running `php artisan cache:clear tfile`. 

Is this expected behavior?

**Comment by ghost** [comment]
Hello,

Is tfile set as your default cache driver?

**Comment by boydcl** [comment]
It is not, but it also shouldn't be. Didn't know `php artisan cache:clear` would only clear the default cache store. I thought it would clear all cache stores. 

Thank you.
